Section "InputClass"
    Identifier "PhotoBooth KeeTouch calibration"
    MatchProduct "HID 1aad:0001"
    MatchUSBID "1aad:0001"
    MatchDevicePath "/dev/input/event*"
    Driver "evdev"
    Option "Mode" "Absolute"
    Option "Calibration" "5640 7620 693 2315"
    Option "SwapAxes" "true"
EndSection
